[tool.poetry]
name = "hhparsertest"
version = "1.0.0"
description = ""
authors = ["DisZom"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.12.0"
msgspec = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
